### K 折交叉验证

输入为 对应的特征，真实预测值，训练模型的类（具备 train 方法和 predict 方法）,K折的折数

返回一个 K 折的平均差值


In [86]:
from bokeh.plotting import figure,show
import numpy as np
def costFunction(x,y):
    if(len(x)!=len(y)):
        raise Exception("the length of y is not equal the length of x")
        return 0
    cost = 0.0
    for i in range(0,len(x)):
        cost += (x[i] - y[i])**2
    cost/=len(x)
    return x

def KFoldValidation(data = None,trueValue = None,modelTrain = None,KNumber = 10):
    ## data : 特征 ，trueValue : 真实的预测值， modelTrain ：训练模型的类  ，KNumber ：K 折验证的 K 值  
    if(len(data)!=len(trueValue)):
        raise Exception("the length of data Y is not equal the length of data X")
        return 0
    
    if(KNumber<=0):
        raise Exception("invalid value of f")
        return 0
    
    dataFold = []
    predictFold = []
    splitLen = int(len(data)/KNumber)
   
    for i in range(0,KNumber):
        dataFold.append(data[i*splitLen:(i+1)*splitLen])
        predictFold.append(trueValue[i*splitLen:(i+1)*splitLen])
        
    errorValue = 0.0 # K 折训练的所有差值的平均值
    plot = figure() # 可视化组件
    
    for i in range(0,KNumber):
        popData = dataFold.pop(i)
        popPredict = predictFold.pop(i)
        trains = tuple([i for i in dataFold])
        predicts = tuple([i for i in predictFold])
        model = modelTrain.train(trains, predicts)
        error = costFunction(model.predict(popData), popPredict)/KNumber
        errorValue += error 
        plot.vbar(x = i,top = error,bottom = 0,width = 0.3) # 绘制直方图
        dataFold.insert(i, popData)
        predictFold.insert(i, popPredict)
    show(plot) # 绘图
    return errorValue
        

### 下面是一个线性回归模型类的示例

In [87]:
import numpy as np

class model:
    def __init__(self,learningRate = None,iteration = None):
        self.x = np.array([])
        if(learningRate!=None and learningRate>0):
            self.learningRate = learningRate
        else:
            self.learningRate = 0.001
        if(iteration!=None and iteration>0):
            self.iteration = iteration
        else:
            self.iteration = 10000
        
    def train(self,feature,predict,learningRate = None,iteration=None):
        if(len(feature.shape)<=1):
            raise Exception('the size of input data shall be [ data amount , feature size]')
        else:
            self.x = np.random.random([len(feature[0])])
            
        if(learningRate!=None and learningRate>0):
            self.learningRate = learningRate
        if(iteration!=None and iteration>0):
            self.iteration = iteration
            
        self.x = self.gredientDecent(feature,predict)
        
    def gredientDecent(self,feature,predictActual):
        for i in range(0,self.iteration):
            predict = self.predict(feature[i])[0]
            self.x -= self.learningRate * ( predict - predictActual[i] ) * self.x
                
    def predict(self,feature):
        if(len(feature.shape)==1):
            if(feature.shape!=self.x.shape):
                raise Exception('input feature size error')
                return 0
            else:
                return np.dot(self.x,feature.reshape(len(feature),1))
        elif(len(feature.shape)==2):
            return np.dot(feature,self.x.reshape(len(self.x),1))
        else:
            raise Exception('feature size is not correct')
            return 0

### 下面是一个与 python 异常相关的实现
分别为继承了 Exception 异常基类的自定义异常类 error
以及在异常抛出后针对不同 exception 类型捕捉后进行的相应不同处理
每一个 try 对应了一个 finally （可选），即每次 try 后无论结果如何都会处理的行为

In [88]:
class error(Exception):
    def __init__(self,value):
        self.value = value
    def msg(self):
        pass
    def __str__(self):
        return self.value

def raiseError(msg):
    pass
    #raise error(msg)

    
def errorRaise(msg):
    try:
        try:
            f = raiseError(msg)
        except ConnectionAbortedError:
            print('ioerror here')
        except IOError:
            print('IO error')
        except error as e:
            print(e)
        except:
            print('unknown error')
        finally:
            print('finally 是无论 try 执行结果如何都会执行的行为')
    except:
        pass
    finally:
        print('外层 finally 处理对应外层 try')
errorRaise('df')

finally 是无论 try 执行结果如何都会执行的行为
外层 finally 处理对应外层 try


In [85]:
KFoldValidation(data = np.array([[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9]]),trueValue = np.array([1,2,3,4,5,6,7,8,9]),modelTrain = model(),KNumber = 3)

[array([[1, 1],
       [2, 2],
       [3, 3]])]
[array([[1, 1],
       [2, 2],
       [3, 3]]), array([[4, 4],
       [5, 5],
       [6, 6]])]
[array([[1, 1],
       [2, 2],
       [3, 3]]), array([[4, 4],
       [5, 5],
       [6, 6]]), array([[7, 7],
       [8, 8],
       [9, 9]])]
[[4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]
predictActual
[[4 5 6]
 [7 8 9]]
predict
4.81026905566
self.x
[ 0.30924268  0.89332459]
minus


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [82]:
data = np.array([[1,1],[2,2],[3,3],[4,4],[5,5]])
splitLen = int(len(data)/10)
print(splitLen)
dataFold = []
for i in range(0,10):
    dataFold.append(data[i*splitLen:(i+1)*splitLen])
dataFold

0


[array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32)]